# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: text.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'text.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntext.proto\x12\ttranslate\" \n\nAudioBytes\x12\x12\n\naudioBytes\x18\x01 \x01(\x0c\"\x1c\n\x0cTextResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\x95\x01\n\x12TranslationService\x12;\n\x0eSendAudioBytes\x12\x15.translate.AudioBytes\x1a\x10.translate.Empty(\x01\x12\x42\n\x13ReceiveTextResponse\x12\x10.translate.Empty\x1a\x17.translate.TextResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'text_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOBYTES']._serialized_start=25
  _globals['_AUDIOBYTES']._serialized_end=57
  _globals['_TEXTRESPONSE']._serialized_start=59
  _globals['_TEXTRESPONSE']._serialized_end=87
  _globals['_EMPTY']._serialized_start=89
  _globals['_EMPTY']._serialized_end=96
  _globals['_TRANSLATIONSERVICE']._serialized_start=99
  _globals['_TRANSLATIONSERVICE']._serialized_end=248
# @@protoc_insertion_point(module_scope)
