# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import text_pb2 as text__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in text_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TranslationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendAudioBytes = channel.unary_unary(
                '/translate.TranslationService/SendAudioBytes',
                request_serializer=text__pb2.AudioBytes.SerializeToString,
                response_deserializer=text__pb2.Empty.FromString,
                _registered_method=True)
        self.ReceiveTextResponse = channel.unary_stream(
                '/translate.TranslationService/ReceiveTextResponse',
                request_serializer=text__pb2.Empty.SerializeToString,
                response_deserializer=text__pb2.TextResponse.FromString,
                _registered_method=True)


class TranslationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendAudioBytes(self, request, context):
        """Client sends a message
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveTextResponse(self, request, context):
        """Server streams messages to client
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TranslationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendAudioBytes': grpc.unary_unary_rpc_method_handler(
                    servicer.SendAudioBytes,
                    request_deserializer=text__pb2.AudioBytes.FromString,
                    response_serializer=text__pb2.Empty.SerializeToString,
            ),
            'ReceiveTextResponse': grpc.unary_stream_rpc_method_handler(
                    servicer.ReceiveTextResponse,
                    request_deserializer=text__pb2.Empty.FromString,
                    response_serializer=text__pb2.TextResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'translate.TranslationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('translate.TranslationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TranslationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendAudioBytes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/translate.TranslationService/SendAudioBytes',
            text__pb2.AudioBytes.SerializeToString,
            text__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReceiveTextResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/translate.TranslationService/ReceiveTextResponse',
            text__pb2.Empty.SerializeToString,
            text__pb2.TextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
